// Type sources, in order of preference:
//
// 1. Generated (./generated/) - everything that mirrors a server-local DTO in
//    inkwash-server/src/models.rs. Regenerated by ts-rs on `cargo test`;
//    do not edit.
// 2. Handwritten below - only the types that mirror the git-pinned
//    `inkwash-logic` crate (../inkwash/logic/src), which carries no ts-rs
//    derives and cannot be modified from this repo without pushing a rev bump.
//    These copies are the admin-ui's view of the firmware wire contract
//    (docs: ../inkwash/docs/sync-api.md); if you change one, change both.

// --- mirrors of inkwash-logic (alarm_schedule::Repeat) ----------------------

/** Weekdays are 0=Sunday..6=Saturday; month days are 1..=31. */
export type Repeat =
  | "Daily"
  | { Weekly: { days: number[] } }
  | { Monthly: { days: number[] } }
  | { Once: { year: number; month: number; day: number } };

// --- mirrors of inkwash-logic (alarm_schedule::StoredAlarm) ------------------

export interface Alarm {
  id: number;
  hour: number;
  minute: number;
  repeat: Repeat;
  enabled: boolean;
  label: string;
}

// --- mirrors of inkwash-logic (todo::{Importance, TodoDue, Todo}) ------------

export type Importance = "low" | "medium" | "high";

export interface TodoDue {
  year: number;
  month: number;
  day: number;
}

export interface Todo {
  id: number;
  text: string;
  done: boolean;
  importance: Importance;
  due_date: TodoDue | null;
  repeat: Repeat | null;
}

// Request payloads mirroring models.rs UpsertAlarmRequest/UpsertTodoRequest;
// handwritten because they embed the inkwash-logic types above.
export interface UpsertAlarmInput {
  hour: number;
  minute: number;
  repeat: Repeat;
  enabled: boolean;
  label: string;
}

export interface UpsertTodoInput {
  text: string;
  done: boolean;
  importance: Importance;
  due_date: TodoDue | null;
  repeat: Repeat | null;
}

// --- mirrors of inkwash-logic (inbox_item::{InboxKind, Priority, InboxItem}) --

export type InboxKind = "alert" | "event" | "info";
export type InboxPriority = "normal" | "high";

export interface InboxItem {
  id: number;
  kind: InboxKind;
  priority: InboxPriority;
  title: string;
  body: string;
  when: number | null;
  read: boolean;
}

// --- generated from src/models.rs (ts-rs, via `cargo test`) ------------------
// Committed because this repo has no CI drift gate; refresh with cargo test.

export type { AccountSummary } from "./generated/AccountSummary";
export type { Channel } from "./generated/Channel";
export type { ChannelCreated } from "./generated/ChannelCreated";
export type { Device } from "./generated/Device";
