#!/usr/bin/env bash
# Build the inkwash-server release binary.
#
#   1. Reuses the same first-run setup as scripts/start.sh:
#      - ensures .env exists with a fresh ADMIN_TOKEN if missing
#      - installs admin-ui/node_modules if missing (one-time per clone)
#   2. Runs `cargo build --release`. build.rs calls `npm run build` in
#      admin-ui/ and rust-embed bakes the result into the binary, so no
#      separate static-asset step is required.
#
# Usage:
#   scripts/build.sh                       # native target
#   scripts/build.sh --target x86_64-unknown-linux-gnu
#   scripts/build.sh --target x86_64-apple-darwin
#
# Set CARGO_TARGET_DIR to relocate build artifacts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

TARGET=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      [[ $# -ge 2 ]] || { echo "error: --target requires a value" >&2; exit 1; }
      TARGET="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '3,16p' "$0"
      exit 0
      ;;
    *)
      echo "error: unknown argument '$1'" >&2
      exit 1
      ;;
  esac
done

for tool in cargo node npm openssl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: '$tool' is required but not found on PATH" >&2
    case "$tool" in
      node|npm) echo "  install Node.js (e.g. 'brew install node') and re-run" >&2 ;;
      openssl)  echo "  install OpenSSL (ships with macOS; on Linux: 'apt install openssl')" >&2 ;;
      cargo)    echo "  install Rust (https://rustup.rs) and re-run" >&2 ;;
    esac
    exit 1
  fi
done

ENV_FILE="$PROJECT_ROOT/.env"
NEED_TOKEN=0
if [[ ! -f "$ENV_FILE" ]]; then
  NEED_TOKEN=1
elif ! grep -Eq '^[[:space:]]*ADMIN_TOKEN=[^[:space:]]+' "$ENV_FILE"; then
  # .env exists but ADMIN_TOKEN is absent, commented out, or blank -
  # treat it as missing rather than blowing up later with a confusing
  # auth error from the server.
  NEED_TOKEN=1
fi

if [[ "$NEED_TOKEN" -eq 1 ]]; then
  TOKEN="$(openssl rand -hex 32)"
  if [[ -f "$ENV_FILE" ]]; then
    printf '\nADMIN_TOKEN=%s\n' "$TOKEN" >> "$ENV_FILE"
    echo "appended fresh ADMIN_TOKEN to existing $ENV_FILE"
  else
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/build.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep ADMIN_TOKEN secret - anyone with it can manage devices, alarms, and todos.
ADMIN_TOKEN=$TOKEN
EOF
    echo "generated $ENV_FILE with a fresh ADMIN_TOKEN"
  fi
fi

ADMIN_UI_DIR="$PROJECT_ROOT/admin-ui"
if [[ ! -d "$ADMIN_UI_DIR/node_modules" ]]; then
  echo "installing admin-ui dependencies (one-time)..."
  (cd "$ADMIN_UI_DIR" && npm install)
fi

CARGO_ARGS=(build --release)
if [[ -n "$TARGET" ]]; then
  CARGO_ARGS+=(--target "$TARGET")
fi

echo "running: cargo ${CARGO_ARGS[*]}"
cargo "${CARGO_ARGS[@]}"

if [[ -n "$TARGET" ]]; then
  BIN_DIR="$PROJECT_ROOT/target/$TARGET/release"
else
  BIN_DIR="$PROJECT_ROOT/target/release"
fi
echo "build complete: $BIN_DIR/inkwash-server"