#!/usr/bin/env bash
# Start the inkpaper-server: handle first-run setup, then launch.
#
#   1. Ensures .env exists in the project root. If ADMIN_TOKEN is missing,
#      generates a fresh random one (required by the server).
#   2. Ensures admin-ui/node_modules exists. If missing, runs
#      `npm install --prefix admin-ui` (one-time per clone).
#   3. Runs `cargo run --release` in the foreground. build.rs + rust-embed
#      bake the admin-ui into the binary, so no extra static files to ship.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

for tool in cargo node npm openssl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: '$tool' is required but not found on PATH" >&2
    case "$tool" in
      node|npm) echo "  install Node.js (e.g. 'brew install node') and re-run" >&2 ;;
      openssl)  echo "  install OpenSSL (ships with macOS; on Linux: 'apt install openssl')" >&2 ;;
      cargo)    echo "  install Rust (https://rustup.rs) and re-run" >&2 ;;
    esac
    exit 1
  fi
done

ENV_FILE="$PROJECT_ROOT/.env"
NEED_TOKEN=0
if [[ ! -f "$ENV_FILE" ]]; then
  NEED_TOKEN=1
elif ! grep -Eq '^[[:space:]]*ADMIN_TOKEN=[^[:space:]]+' "$ENV_FILE"; then
  # .env exists but ADMIN_TOKEN is absent, commented out, or blank -
  # treat it as missing rather than blowing up later with a confusing
  # auth error from the server.
  NEED_TOKEN=1
fi

if [[ "$NEED_TOKEN" -eq 1 ]]; then
  TOKEN="$(openssl rand -hex 32)"
  if [[ -f "$ENV_FILE" ]]; then
    printf '\nADMIN_TOKEN=%s\n' "$TOKEN" >> "$ENV_FILE"
    echo "appended fresh ADMIN_TOKEN to existing $ENV_FILE"
  else
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep ADMIN_TOKEN secret - anyone with it can manage devices, alarms, and todos.
ADMIN_TOKEN=$TOKEN
EOF
    echo "generated $ENV_FILE with a fresh ADMIN_TOKEN"
  fi
fi

ADMIN_UI_DIR="$PROJECT_ROOT/admin-ui"
if [[ ! -d "$ADMIN_UI_DIR/node_modules" ]]; then
  echo "installing admin-ui dependencies (one-time)..."
  (cd "$ADMIN_UI_DIR" && npm install)
fi

echo "starting inkpaper-server (Ctrl+C to stop)..."
exec cargo run --release
